version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      tensorflow:
        patterns:
          - '@tensorflow/*'
      rollup:
        patterns:
          - 'rollup'
          - '@rollup/*'
          - 'rollup-plugin-*'
      types:
        patterns:
          - '@types/*'
      dev-tooling:
        patterns:
          - '@biomejs/*'
          - 'husky'
          - 'lint-staged'
          - 'typescript'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
